// <auto-generated />
namespace Lesson5_200406015.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CarModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201906102337015_CarModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
